blueprint:
  name: Hue Manual Override Detector
  description: >
    Detects manual changes to a Hue light (brightness, color, etc.) and sets
    an override flag for a configurable timeout to pause other automations.
  domain: automation
  input:
    hue_light:
      name: Hue Light
      description: The Hue lamp or group to monitor for manual changes.
      selector:
        entity:
          domain: light
    override_helper:
      name: Override Helper
      description: The input_boolean helper to set when override is active.
      selector:
        entity:
          domain: input_boolean
    override_timeout:
      name: Override Timeout (minutes)
      description: How long to keep override active after manual change.
      default: 30
      selector:
        number:
          min: 5
          max: 240
          step: 5
          unit_of_measurement: minutes

trigger:
  - platform: state
    entity_id: !input hue_light

condition:
  - condition: template
    value_template: >
      {{ trigger.to_state.attributes.brightness != trigger.from_state.attributes.brightness
         or trigger.to_state.attributes.color_temp != trigger.from_state.attributes.color_temp
         or trigger.to_state.attributes.rgb_color != trigger.from_state.attributes.rgb_color }}

action:
  - service: input_boolean.turn_on
    target:
      entity_id: !input override_helper
  - delay:
      minutes: !input override_timeout
  - service: input_boolean.turn_off
    target:
      entity_id: !input override_helper

mode: restart
