blueprint:
  name: Hue All-Day Scene with Manual Override
  description: >
    Automate Philips Hue scene changes based on time of day, only if the physical switch and Hue light are ON.
    Supports pausing automation when manual control is detected.
  domain: automation
  input:
    physical_switch:
      name: Physical Switch
      description: The physical on/off switch controlling power.
      selector:
        entity:
          domain: switch
    hue_light:
      name: Hue Light
      description: The Hue lamp or group to control.
      selector:
        entity:
          domain: light
    morning_scene:
      name: Morning Scene
      selector:
        entity:
          domain: scene
    day_scene:
      name: Day Scene
      selector:
        entity:
          domain: scene
    evening_scene:
      name: Evening Scene
      selector:
        entity:
          domain: scene
    night_scene:
      name: Night Scene
      selector:
        entity:
          domain: scene
    late_night_scene:
      name: Late Night Scene
      selector:
        entity:
          domain: scene
    override_timeout:
      name: Override Timeout (minutes)
      description: How long to pause schedule after manual control.
      default: 30
      selector:
        number:
          min: 5
          max: 240
          step: 5
          unit_of_measurement: minutes

trigger:
  - platform: time_pattern
    minutes: "/5"
  - platform: state
    entity_id: !input physical_switch
    to: "on"
  - platform: state
    entity_id: !input hue_light
    to: "on"
  - platform: state
    entity_id: !input hue_light

condition:
  - condition: state
    entity_id: !input physical_switch
    state: "on"
  - condition: state
    entity_id: !input hue_light
    state: "on"
  - condition: state
    entity_id: "input_boolean.override_{{ hue_light.split('.')[-1] }}"
    state: "off"

action:
  - choose:
      - conditions:
          - condition: time
            after: "06:00:00"
            before: "08:00:00"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input morning_scene
      - conditions:
          - condition: time
            after: "08:00:00"
            before: "20:57:00"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input day_scene
      - conditions:
          - condition: time
            after: "20:57:00"
            before: "22:00:00"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input evening_scene
      - conditions:
          - condition: time
            after: "22:00:00"
            before: "00:00:00"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input night_scene
      - conditions:
          - condition: time
            after: "00:00:00"
            before: "06:00:00"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input late_night_scene
mode: restart
